# Generated by Django 5.1.4 on 2024-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='etudes',
        ),
        migrations.AddField(
            model_name='note',
            name='scales',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
